language: ruby

dist: trusty

rvm:
- "2.2.7"
- "2.3.4"

sudo: false

cache: bundler

script:
  - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem
  - ./test_loading_provider.sh

deploy:
  provider: rubygems
  api_key:
    secure: ZmZoDL1tilWvQrqRWDm2K4xQ5Grt9eRJzYVZPLANR0P1TM5BJBLk+UhWCWCPkkDVIBWMa5ANsiFYBxtH65Lw+uqMztSpVusk0l0LQXZGv9jMpT9445A8008U3vvfS0ke7IG8Q4bMAC7Sd6VGaiHDyZC7zmNvnqMpmVX7ShcgBME=
  gem: dpl
  on:
    repo: travis-ci/dpl
    ruby: 2.3.4

notifications:
  webhooks: "http://requestb.in/1guaq7t1"
